tekt/models.py
from flask.ext.sqlalchemy import SQLAlchemy

# create instance of sqlalchemy
db = SQLAlchemy()


class PropertyModel(db.Model):

    """ Property model. """

    __tablename__ = 'properties'
    id = db.Column(db.Integer, primary_key=True)
    property = db.Column(db.String(100), unique=True)
    paths = db.relationship('PathModel', backref='property', cascade='delete')


class PathPageModel(db.Model):

    """ Path to Page model. """

    __tablename__ = 'path_pages'
    id = db.Column(db.Integer, primary_key=True)
    path_id = db.Column(db.Integer, db.ForeignKey('paths.id'))
    page_id = db.Column(db.Integer, db.ForeignKey('pages.id'))
    effective_date = db.Column(db.DateTime)
    expiration_date = db.Column(db.DateTime)
    page = db.relationship("PageModel", backref="path_page")


class PathModel(db.Model):

    """ Path model """

    __tablename__ = 'paths'
    id = db.Column(db.Integer, primary_key=True)
    path = db.Column(db.String(100))
    property_id = db.Column(db.Integer, db.ForeignKey('properties.id'))
    pages = db.relationship("PathPageModel", backref="path", cascade='delete')


class PageModel(db.Model):

    """ Page model """

    __tablename__ = 'pages'
    id = db.Column(db.Integer, primary_key=True)
    page = db.Column(db.String(100))

tekt/__init__.py
#! ../env/bin/python
import os

from flask import Flask
from tekt.controllers.main import blueprint as main_blueprint
from tekt.controllers.properties import blueprint as properties_blueprint
from tekt.controllers.paths import blueprint as paths_blueprint
from tekt.controllers.pages import blueprint as pages_blueprint
from tekt.tektonik import tektonik


def create_app(object_name, env="prod"):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. ark.settings.ProdConfig

        env: The name of the current environment, e.g. prod or dev
    """

    app = Flask(__name__)

    app.config.from_object(object_name)
    app.config['ENV'] = env

    # register tektonik
    tektonik.init_app(app)

    # register our blueprints
    app.register_blueprint(main_blueprint, url_prefix='/')
    app.register_blueprint(properties_blueprint, url_prefix='/properties')
    app.register_blueprint(paths_blueprint, url_prefix='/paths')
    app.register_blueprint(pages_blueprint, url_prefix='/pages')

    return app

if __name__ == '__main__':
    # Import the config for the proper environment using the
    # shell var APPNAME_ENV
    env = os.environ.get('APPNAME_ENV', 'prod')
    app = create_app('tekt.settings.%sConfig' % env.capitalize(), env=env)

    app.run()

tekt/controller.py
"""
:synopsis: Main blueprint router and controller
"""

from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from tektonik import tektonik
import forms

controller = Blueprint('router', __name__, template_folder='templates')


@controller.route('/')
def dashboard():

    """ home page """

    return render_template("dashboard.html")


@controller.route('/properties')
def properties():

    """ get list of properties """

    records = tektonik.list_properties()['result']
    return render_template("properties.html", properties=records)


@controller.route('/properties/create', methods=['GET', 'POST'])
def create_property():

    """ create a property """

    form = forms.PropertyForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_property(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            return redirect(url_for('.properties'))
    return render_template("properties-create.html", form=form)


@controller.route('/properties/<int:id>')
def read_property(id):

    """ read a property """

    record = tektonik.read_property(id)['result']
    return render_template("properties-read.html", property=record)


@controller.route('/properties/<int:id>/update', methods=['GET', 'POST'])
def update_property(id):

    """ edit a property """

    record = tektonik.read_property(id)['result']
    form = forms.PropertyForm(request.form, data=record)

    if request.method == 'POST':
        form = forms.PropertyForm(request.form)
        update_record = tektonik.update_property(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            return redirect(url_for('.properties'))

    template = "properties-update.html"
    return render_template(template, form=form, property=record)


@controller.route('/properties/<int:id>/delete')
def delete_property(id):

    """ delete a property """

    tektonik.delete_property(id)
    return redirect(url_for('.properties'))

tekt/controllers/main.py
"""
:synopsis: Main Blueprint and controller
"""

from flask import Blueprint
from flask import g
from flask import render_template
from tekt import forms
from flask import request
from tekt.tektonik import tektonik


blueprint = Blueprint('main', __name__, template_folder='templates')


@blueprint.before_app_request
def before_app_request():

    """ Manage and generate global template vars """

    g.template = {}
    g.template['menu-toggle'] = 'collapsed' \
        if request.cookies.get('TEKT-menu-toggle') == 'true' else ''
    g.template['menu-toggle-button'] = 'fa-chevron-right' \
        if request.cookies.get('TEKT-menu-toggle') == 'true' \
        else 'fa-chevron-left'


@blueprint.route('')
def home():

    """ home page """

    form = forms.SignInForm(request.form)
    return render_template("home.html", form=form)


@blueprint.route('dashboard')
def dashboard():

    """ dashboard """

    properties = tektonik.list_properties()['result']
    return render_template(
        "dashboard.html",
        properties=properties,
        section='dashboard')


@blueprint.route('primers')
def primers():

    """ Help tutorials """

    return render_template("primers.html", section='primers')

tekt/controllers/pages.py
"""
:synopsis: Pages controller
"""

from flask import Blueprint
from tekt.messaging import pages as messaging
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt.tektonik import tektonik
from tekt import forms

blueprint = Blueprint('pages', __name__, template_folder='templates')


@blueprint.route('/')
def list_pages():

    """ get list of pages """

    pages = tektonik.list_pages()
    records = pages['result']
    metadata = pages['metadata']
    return render_template(
        "pages/list.html",
        pages=records,
        metadata=metadata,
        section='pages')


@blueprint.route('/search', methods=['GET', 'POST'])
def search_pages():

    """ get list of pages """

    form = forms.PageSearchForm(request.form)
    if request.method == 'GET':
        records = tektonik.list_pages()['result']

    if request.method == 'POST':
        term = {'page': request.form['term']}
        records = tektonik.search_pages(term)['result']

    return render_template("selectors/pages.html", pages=records, form=form)


@blueprint.route('/create', methods=['GET', 'POST'])
def create_page():

    """ create a page """

    form = forms.PageForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_page(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_page_success)
            return redirect(url_for('.list_pages'))
        else:
            messaging.flash(messaging.create_page_error)
    return render_template("pages/create.html", form=form, section='pages')


@blueprint.route('/<int:id>')
def read_page(id):

    """ read a page """

    record = tektonik.read_page(id)['result']
    return render_template("pages/read.html", page=record, section='pages')


@blueprint.route('/<int:id>/paths', methods=['GET', 'POST'])
def path_schedule(id):

    """ view and add pages """

    record = tektonik.read_page(id)['result']
    data = {'path_id': id, 'page_id': 0}
    form = forms.PathPageForm(request.form, data=data)

    if request.method == 'POST':
        new_record = tektonik.create_path_page(request.form)
        is_valid = forms.is_valid(
            form,
            new_record,
            {'page_id': 'page_selector'}
        )
        if is_valid:
            messaging.flash(messaging.page_schedule_success)
            return redirect(url_for('.page_schedule', id=id))
        else:
            messaging.flash(messaging.page_schedule_error)

    return render_template(
        'pages/path_schedule.html',
        page=record,
        form=form,
        section='pages'
    )


@blueprint.route('/<int:id>/remove/<int:path_page_id>', methods=['GET'])
def remove_path(id, path_page_id):

    """ remove a page from a path """

    tektonik.delete_path_page(path_page_id)
    messaging.flash(messaging.remove_path_success)
    return redirect(url_for('.path_schedule', id=id))


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_page(id):

    """ edit a page """

    record = tektonik.read_page(id)['result']
    form = forms.PageForm(request.form, data=record)
    delete_form = forms.DeletePageForm(phrase=record['page'])

    if request.method == 'POST':
        form = forms.PageForm(request.form)
        update_record = tektonik.update_page(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_page_success)
            return redirect(url_for('.read_page', id=id))
        else:
            messaging.flash(messaging.update_page_error)

    template = "pages/update.html"
    return render_template(
        template,
        form=form,
        delete_form=delete_form,
        page=record,
        section='pages')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_page(id):

    """ delete a page """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_page_success,
            phrase=request.form['phrase'])
        tektonik.delete_page(id)
        return redirect(url_for('.list_pages'))
    else:
        messaging.flash(messaging.delete_page_error)
        return redirect(url_for('.read_page', id=id))

tekt/controllers/paths.py
"""
:synopsis: Paths controller
"""

from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt import forms
from tekt.messaging import paths as messaging
from tekt.tektonik import tektonik

blueprint = Blueprint('paths', __name__, template_folder='templates')


@blueprint.route('/')
def list_paths():

    """ get list of paths """

    paths = tektonik.list_paths()
    records = paths['result']
    metadata = paths['metadata']
    return render_template(
        "paths/list.html",
        paths=records,
        metadata=metadata,
        section='paths')


@blueprint.route('/create', methods=['GET', 'POST'])
def create_path():

    """ create a path """

    form = forms.path_form_factory(request)
    if request.method == 'POST':
        new_record = tektonik.create_path(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_path_success)
            return redirect(url_for('.list_paths'))
        else:
            messaging.flash(messaging.create_path_error)
    return render_template("paths/create.html", form=form, section='paths')


@blueprint.route('/<int:id>', methods=['GET', 'POST'])
def read_path(id):

    """ read a path and add page to path """

    record = tektonik.read_path(id)['result']

    return render_template(
        "paths/read.html",
        path=record,
        section='paths')


@blueprint.route('/<int:id>/pages', methods=['GET', 'POST'])
def page_schedule(id):

    """ view and add pages """

    record = tektonik.read_path(id)['result']
    data = {'path_id': id, 'page_id': 0}
    form = forms.PathPageForm(request.form, data=data)

    if request.method == 'POST':
        new_record = tektonik.create_path_page(request.form)
        is_valid = forms.is_valid(
            form,
            new_record,
            {'page_id': 'page_selector'}
        )
        if is_valid:
            messaging.flash(messaging.page_schedule_success)
            return redirect(url_for('.page_schedule', id=id))
        else:
            messaging.flash(messaging.page_schedule_error)

    return render_template(
        'paths/page_schedule.html',
        path=record,
        form=form,
        section='paths'
    )


@blueprint.route('/<int:id>/remove/<int:path_page_id>', methods=['GET'])
def remove_page(id, path_page_id):

    """ remove a page from a path """

    tektonik.delete_path_page(path_page_id)
    messaging.flash(messaging.remove_page_success)
    return redirect(url_for('.page_schedule', id=id))


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_path(id):

    """ edit a path """

    record = tektonik.read_path(id)['result']
    path_form = forms.path_form_factory(request, data=record)
    delete_form = forms.DeletePageForm(phrase=record['path'])

    if request.method == 'POST':
        form = forms.path_form_factory(request)
        update_record = tektonik.update_path(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_path_success)
            return redirect(url_for('.read_path', id=id))
        else:
            messaging.flash(messaging.update_path_error)

    template = "paths/update.html"
    return render_template(
        template,
        path_form=path_form,
        path=record,
        delete_form=delete_form,
        section='paths')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_path(id):

    """ delete a path """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_path_success,
            phrase=request.form['phrase'])
        tektonik.delete_path(id)
        return redirect(url_for('.list_paths'))
    else:
        messaging.flash(messaging.delete_path_error)
        return redirect(url_for('.read_path', id=id))

tekt/controllers/properties.py
"""
:synopsis: Properties controller
"""

from flask import Blueprint
from tekt.messaging import properties as messaging
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt import forms
from tekt.tektonik import tektonik


blueprint = Blueprint('properties', __name__, template_folder='templates')


@blueprint.route('/')
def list_properties():

    """ get list of properties """
    properites = tektonik.list_properties()
    records = properites['result']
    metadata = properites['metadata']
    return render_template(
        "properties/list.html",
        properties=records,
        metadata=metadata,
        section='properties')


@blueprint.route('/create', methods=['GET', 'POST'])
def create_property():

    """ create a property """

    form = forms.PropertyForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_property(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_property_success)
            return redirect(url_for('.list_properties'))
        else:
            messaging.flash(messaging.create_property_error)
    return render_template(
        "properties/create.html",
        form=form,
        section='properties')


@blueprint.route('/<int:id>')
def read_property(id):

    """ read a property """

    record = tektonik.read_property(id)['result']
    return render_template(
        "properties/read.html",
        property=record,
        section='properties')


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_property(id):

    """ edit a property """

    record = tektonik.read_property(id)['result']
    form = forms.PropertyForm(request.form, data=record)
    delete_form = forms.DeletePropertyForm(phrase=record['property'])

    if request.method == 'POST':
        form = forms.PropertyForm(request.form)
        update_record = tektonik.update_property(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_property_success)
            return redirect(url_for('.read_property', id=id))
        else:
            messaging.flash(messaging.update_property_error)

    template = "properties/update.html"
    return render_template(
        template,
        form=form,
        delete_form=delete_form,
        property=record,
        section='properties')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_property(id):

    """ delete a property """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_property_success,
            phrase=request.form['phrase'])
        tektonik.delete_property(id)
        return redirect(url_for('.list_properties'))
    else:
        messaging.flash(messaging.delete_property_error)
        return redirect(url_for('.read_property', id=id))

tekt/templates/paths/create.html
{% from "macros/forms.html" import render_field %} 
{% extends 'template.html' %} 

{% block body %}
<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>

<form method="post" action="{{ url_for('.create_path') }}">
    <legend>New</legend>
    <fieldset>
        {{ render_field(form.path, autofocus='autofocus', placeholder="Example: /my/path") }}
    </fieldset>
    <fieldset>
        {{ render_field(form.property_id) }}
    </fieldset>
    <footer>
        <button type="submit"><i class="fa fa-check"></i> Save</button>
        <a class="button" href="{{ url_for('.list_paths') }}"><i class="fa fa-close"></i> Cancel</a>
    </footer>
</form>
{% endblock %}

tekt/templates/paths/list.html
{% extends 'template.html' %}
{% block body %}


<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>

<div class="card">
<header>
            <h2 class="title">{{paths|length}} of {{metadata.total_records}}</h2>
            <div class="actions">
                <a class="button" href="{{ url_for('.create_path') }}"><i class="fa fa-plus"></i> New</a>
            </div>
</header>
<div class="content">
    <table class="data">
        <tr>
            <th>Path</th>
            <th>Property</th>
            <th>Pages</th>
        </tr>
        {% for record in paths %}
        <tr>
            <td><a black href="{{ url_for('.read_path', id=record.id) }}">{{record.path}}</a></td>
            <td>{{record.property.property}}</td>
            <td>{{record.pages|length}}</td>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
</div>



{% endblock %}

tekt/templates/paths/page_schedule.html
{% from "macros/forms.html" import render_field, render_hidden_field %} 
{% extends 'template.html' %}
{% block body %}

<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>
<h2>
    <a black href="{{ url_for('paths.read_path', id=path.id) }}">{{path.path}}</a>
</h2>
<div class="card">
    <header>
        <h2 class="title">Page Schedule</h2>
        <div class="actions">
            <a tekt-scroller="target=add_page" class="button small"><i class="fa fa-arrow-down"></i> Schedule New Page</a>
        </div>
    </header>
    <div class="content">
        <table class="data">
            <tr>
                <th>#</th>
                <th>page</th>
                <th>effective</th>
                <th>expires</th>
                <th>actions</th>
            </tr>
            {% for page in path.pages %}
            <tr>
                <td>{{ page.id }}</td>
                <td><a href="{{ url_for('pages.read_page', id=page.id) }}">{{ page.page }}</a></td>
                <td>{{page.effective_date_humanized}}</td>
                <td>{{page.expiration_date_humanized}}</td>
                <td><a href="{{ url_for('paths.remove_page', id=path.id, path_page_id=page.path_page_id)}}" tekt-dialog="type=confirm|message=Are you sure you want to remove this page from this path?"> remove</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

{{form.errors}}
<form id="add_page" tekt-id="add_page" method="post" action="{{ url_for('paths.page_schedule', id=path.id) }}">
    <legend>Schedule Page</legend>
        {{ render_hidden_field(form.path_id) }}
        {{ render_hidden_field(form.page_id) }}
        <fieldset>
            {{ 
                render_field(form.page_selector, 
                placeholder="Click to select", 
                readonly="readonly", 
                **{'tekt-selector':'page'}) 
            }}
        </fieldset>
        <fieldset>
            {{ 
                render_field(form.effective_date, 
                placeholder="Example: 12/25/2025 5:00pm",
                **{'tekt-mask':'datetime'})
            }}
        </fieldset>
        <fieldset tekt-id="expiration_date_fieldset" class="{% if form.is_persistent.data: %}disabled{% endif %}">
            {% if form.is_persistent.data: %}
                {{ render_field(form.expiration_date, **{'disabled':'disabled'})  }}
            {% else %}
                {{ render_field(form.expiration_date)  }}
            {% endif %}
        </fieldset>
        <fieldset>
            {{ render_field(form.is_persistent, **{'tekt-disable':'expiration_date_fieldset'}) }}
        </fieldset>
    <footer>
        <button type="submit"><i class="fa fa-plus"></i> Schedule</button> 
    </footer>
</form>



{% endblock %}

tekt/templates/paths/pages.html
{% from "macros/forms.html" import render_field, render_hidden_field %} 
{% extends 'template.html' %}
{% block body %}


<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>
<h2>
    <a black href="{{ url_for('paths.read_path', id=path.id) }}">{{path.path}}</a>
</h2>

<div class="card">
    <header>
        <h2 class="title">Page Schedule</h2>
        <div class="actions">
            <a href="#add_page" class="button">Add</a>
        </div>
    </header>
    <div class="content">
        <table class="data">
            <tr>
                <th>#</th>
                <th>page</th>
                <th>actions</th>
            </tr>
            {% for page in path.pages %}
            <tr>
                <td>{{ page.id }}</td>
                <td><a black href="{{ url_for('pages.read_page', id=page.id) }}">{{ page.page }}</a>
                </td>
                <td><a black href="{{ url_for('paths.remove_page', id=path.id, path_page_id=page.path_page_id)}}">remove</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

<form id="add_page" method="post" action="{{ url_for('paths.pages', id=path.id) }}">
    <legend>Add Page</legend>
        <fieldset>
            <ul class="list">
                {{ render_hidden_field(form.path_id) }}
                {{ render_hidden_field(form.page_id) }} 
                {{ 
                    render_field(form.page_selector, 
                    placeholder="Click to Search", 
                    readonly="readonly", 
                    show_description=False,
                    **{'tekt-selector':'page'}) 
                }}
            </ul>
        </fieldset>
    <footer>
        <input class="button" type="submit" value="Add Page">
    </footer>
</form>



{% endblock %}

tekt/templates/paths/read.html
{% extends 'template.html' %} 

{% block body %}

<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>
<h2>
    <a black href="{{ url_for('.read_path', id=path.id) }}">{{path.path}}</a>
</h2>

<div class="card">
<header>
    <h2 class="title">Details</h2>
    <div class="actions">
        <a class="button" href="{{ url_for('.update_path', id=path.id )}}"><i class="fa fa-gear"></i> Edit</a>
    </div>
</header>
<div class="content">
    <table class="data">
        <tr>
            <th>ID</th>
            <td>{{path.id}}</td>
        </tr>
        <tr>
            <th>path</th>
            <td>{{path.path}}</td>
        </tr>
        <tr>
            <th>property</th>
            <td>{{path.property.property}}</td>
        </tr>
    </table>
</div>
</div>
<div class="card">
    <header>
        <h2 class="title">Page Schedule</h2>
        <div class="actions">
            <a class="button" href="{{ url_for('.page_schedule', id=path.id )}}"><i class="fa fa-gear"></i> Edit</a>
        </div>
    </header>
    <div class="content">
        <table class="data">
                <tr>
                    <th>Page</th>
                    <th>Effective</th>
                    <th>Expires</th>
                </tr>
                {% for page in path.pages %}
                <tr>
                    <td><a href="{{ url_for('pages.read_page', id=page.id )}}">{{page.page}}</a></td>
                    <td>{{page.effective_date_humanized}}</td>
                    <td>{{page.expiration_date_humanized}}</td>
                </tr>
                {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

tekt/templates/paths/update.html
{% from "macros/forms.html" import render_field, render_hidden_field %} 
{% extends 'template.html' %} 

{% block body %}
<h1>
    <a black href="{{ url_for('.list_paths') }}">Paths</a>
</h1>
<h2>
    <a black href="{{ url_for('.read_path', id=path.id) }}">{{path.path}}</a>
</h2>
<form method="post" action="{{ url_for('paths.update_path', id=path.id) }}">
    {{ path_form.id }}
    <legend>Edit</legend>
    <fieldset>
        <ul class="list">
            {{ render_field(path_form.path, autofocus="autofocus", placeholder="Example: /my/path") }}
        </ul>
    </fieldset>
    <fieldset>
        <ul class="list">
            {{ render_field(path_form.property_id) }}
        </ul>
    </fieldset>
    <footer>
        <button type="submit"><i class="fa fa-check"></i> Save</button>
        <a class="button" href="{{ url_for('paths.read_path', id=path.id) }}"><i class="fa fa-close"></i> Cancel</a>
    </footer>
</form>

<div class="panel text-right">
    <a class="alarm button link" tekt-showhide="delete_form"><i class="fa fa-trash"></i> Delete</a>
</div>

<form method="post" tekt-id="delete_form" class="view-hidden" action="{{ url_for('.delete_path', id=path.id) }}">
    <legend>Delete Path</legend>
    <fieldset>
        {{ delete_form.phrase }}
        <div class="field">
            {{ delete_form.confirm(placeholder=path_form.path.data)|safe }}
            <p>{{ delete_form.confirm.description }}</p>
        </div>
    </fieldset>
    <footer>
    <div class="actions">
        <button type="submit"><i class="fa fa-check"></i> Confirm</button>
    </footer>
</form>
{% endblock %}