tekt/models.py
from flask.ext.sqlalchemy import SQLAlchemy

# create instance of sqlalchemy
db = SQLAlchemy()


class PropertyModel(db.Model):

    """ Property model. """

    __tablename__ = 'properties'
    id = db.Column(db.Integer, primary_key=True)
    property = db.Column(db.String(100), unique=True)
    paths = db.relationship('PathModel', backref='property', cascade='delete')


class PathPageModel(db.Model):

    """ Path to Page model. """

    __tablename__ = 'path_pages'
    id = db.Column(db.Integer, primary_key=True)
    path_id = db.Column(db.Integer, db.ForeignKey('paths.id'))
    page_id = db.Column(db.Integer, db.ForeignKey('pages.id'))
    effective_date = db.Column(db.DateTime)
    expiration_date = db.Column(db.DateTime)
    page = db.relationship("PageModel", backref="path_page")


class PathModel(db.Model):

    """ Path model """

    __tablename__ = 'paths'
    id = db.Column(db.Integer, primary_key=True)
    path = db.Column(db.String(100))
    property_id = db.Column(db.Integer, db.ForeignKey('properties.id'))
    pages = db.relationship("PathPageModel", backref="path", cascade='delete')


class PageModel(db.Model):

    """ Page model """

    __tablename__ = 'pages'
    id = db.Column(db.Integer, primary_key=True)
    page = db.Column(db.String(100))

tekt/__init__.py
#! ../env/bin/python
import os

from flask import Flask
from tekt.controllers.main import blueprint as main_blueprint
from tekt.controllers.properties import blueprint as properties_blueprint
from tekt.controllers.paths import blueprint as paths_blueprint
from tekt.controllers.pages import blueprint as pages_blueprint
from tekt.tektonik import tektonik


def create_app(object_name, env="prod"):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. ark.settings.ProdConfig

        env: The name of the current environment, e.g. prod or dev
    """

    app = Flask(__name__)

    app.config.from_object(object_name)
    app.config['ENV'] = env

    # register tektonik
    tektonik.init_app(app)

    # register our blueprints
    app.register_blueprint(main_blueprint, url_prefix='/')
    app.register_blueprint(properties_blueprint, url_prefix='/properties')
    app.register_blueprint(paths_blueprint, url_prefix='/paths')
    app.register_blueprint(pages_blueprint, url_prefix='/pages')

    return app

if __name__ == '__main__':
    # Import the config for the proper environment using the
    # shell var APPNAME_ENV
    env = os.environ.get('APPNAME_ENV', 'prod')
    app = create_app('tekt.settings.%sConfig' % env.capitalize(), env=env)

    app.run()

tekt/controller.py
"""
:synopsis: Main blueprint router and controller
"""

from flask import Blueprint
from flask import render_template
from flask import redirect
from flask import request
from flask import url_for
from tektonik import tektonik
import forms

controller = Blueprint('router', __name__, template_folder='templates')


@controller.route('/')
def dashboard():

    """ home page """

    return render_template("dashboard.html")


@controller.route('/properties')
def properties():

    """ get list of properties """

    records = tektonik.list_properties()['result']
    return render_template("properties.html", properties=records)


@controller.route('/properties/create', methods=['GET', 'POST'])
def create_property():

    """ create a property """

    form = forms.PropertyForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_property(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            return redirect(url_for('.properties'))
    return render_template("properties-create.html", form=form)


@controller.route('/properties/<int:id>')
def read_property(id):

    """ read a property """

    record = tektonik.read_property(id)['result']
    return render_template("properties-read.html", property=record)


@controller.route('/properties/<int:id>/update', methods=['GET', 'POST'])
def update_property(id):

    """ edit a property """

    record = tektonik.read_property(id)['result']
    form = forms.PropertyForm(request.form, data=record)

    if request.method == 'POST':
        form = forms.PropertyForm(request.form)
        update_record = tektonik.update_property(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            return redirect(url_for('.properties'))

    template = "properties-update.html"
    return render_template(template, form=form, property=record)


@controller.route('/properties/<int:id>/delete')
def delete_property(id):

    """ delete a property """

    tektonik.delete_property(id)
    return redirect(url_for('.properties'))

tekt/controllers/main.py
"""
:synopsis: Main Blueprint and controller
"""

from flask import Blueprint
from flask import g
from flask import render_template
from tekt import forms
from flask import request
from tekt.tektonik import tektonik


blueprint = Blueprint('main', __name__, template_folder='templates')


@blueprint.before_app_request
def before_app_request():

    """ Manage and generate global template vars """

    g.template = {}
    g.template['menu-toggle'] = 'collapsed' \
        if request.cookies.get('TEKT-menu-toggle') == 'true' else ''
    g.template['menu-toggle-button'] = 'fa-chevron-right' \
        if request.cookies.get('TEKT-menu-toggle') == 'true' \
        else 'fa-chevron-left'


@blueprint.route('')
def home():

    """ home page """

    form = forms.SignInForm(request.form)
    return render_template("home.html", form=form)


@blueprint.route('dashboard')
def dashboard():

    """ dashboard """

    properties = tektonik.list_properties()['result']
    return render_template(
        "dashboard.html",
        properties=properties,
        section='dashboard')


@blueprint.route('primers')
def primers():

    """ Help tutorials """

    return render_template("primers.html", section='primers')

tekt/controllers/pages.py
"""
:synopsis: Pages controller
"""

from flask import Blueprint
from tekt.messaging import pages as messaging
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt.tektonik import tektonik
from tekt import forms

blueprint = Blueprint('pages', __name__, template_folder='templates')


@blueprint.route('/')
def list_pages():

    """ get list of pages """

    pages = tektonik.list_pages()
    records = pages['result']
    metadata = pages['metadata']
    return render_template(
        "pages/list.html",
        pages=records,
        metadata=metadata,
        section='pages')


@blueprint.route('/search', methods=['GET', 'POST'])
def search_pages():

    """ get list of pages """

    form = forms.PageSearchForm(request.form)
    if request.method == 'GET':
        records = tektonik.list_pages()['result']

    if request.method == 'POST':
        term = {'page': request.form['term']}
        records = tektonik.search_pages(term)['result']

    return render_template("selectors/pages.html", pages=records, form=form)


@blueprint.route('/create', methods=['GET', 'POST'])
def create_page():

    """ create a page """

    form = forms.PageForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_page(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_page_success)
            return redirect(url_for('.list_pages'))
        else:
            messaging.flash(messaging.create_page_error)
    return render_template("pages/create.html", form=form, section='pages')


@blueprint.route('/<int:id>')
def read_page(id):

    """ read a page """

    record = tektonik.read_page(id)['result']
    return render_template("pages/read.html", page=record, section='pages')


@blueprint.route('/<int:id>/paths', methods=['GET', 'POST'])
def path_schedule(id):

    """ view and add pages """

    record = tektonik.read_page(id)['result']
    data = {'path_id': id, 'page_id': 0}
    form = forms.PathPageForm(request.form, data=data)

    if request.method == 'POST':
        new_record = tektonik.create_path_page(request.form)
        is_valid = forms.is_valid(
            form,
            new_record,
            {'page_id': 'page_selector'}
        )
        if is_valid:
            messaging.flash(messaging.page_schedule_success)
            return redirect(url_for('.page_schedule', id=id))
        else:
            messaging.flash(messaging.page_schedule_error)

    return render_template(
        'pages/path_schedule.html',
        page=record,
        form=form,
        section='pages'
    )


@blueprint.route('/<int:id>/remove/<int:path_page_id>', methods=['GET'])
def remove_path(id, path_page_id):

    """ remove a page from a path """

    tektonik.delete_path_page(path_page_id)
    messaging.flash(messaging.remove_path_success)
    return redirect(url_for('.path_schedule', id=id))


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_page(id):

    """ edit a page """

    record = tektonik.read_page(id)['result']
    form = forms.PageForm(request.form, data=record)
    delete_form = forms.DeletePageForm(phrase=record['page'])

    if request.method == 'POST':
        form = forms.PageForm(request.form)
        update_record = tektonik.update_page(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_page_success)
            return redirect(url_for('.read_page', id=id))
        else:
            messaging.flash(messaging.update_page_error)

    template = "pages/update.html"
    return render_template(
        template,
        form=form,
        delete_form=delete_form,
        page=record,
        section='pages')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_page(id):

    """ delete a page """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_page_success,
            phrase=request.form['phrase'])
        tektonik.delete_page(id)
        return redirect(url_for('.list_pages'))
    else:
        messaging.flash(messaging.delete_page_error)
        return redirect(url_for('.read_page', id=id))

tekt/controllers/paths.py
"""
:synopsis: Paths controller
"""

from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt import forms
from tekt.messaging import paths as messaging
from tekt.tektonik import tektonik

blueprint = Blueprint('paths', __name__, template_folder='templates')


@blueprint.route('/')
def list_paths():

    """ get list of paths """

    paths = tektonik.list_paths()
    records = paths['result']
    metadata = paths['metadata']
    return render_template(
        "paths/list.html",
        paths=records,
        metadata=metadata,
        section='paths')


@blueprint.route('/create', methods=['GET', 'POST'])
def create_path():

    """ create a path """

    form = forms.path_form_factory(request)
    if request.method == 'POST':
        new_record = tektonik.create_path(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_path_success)
            return redirect(url_for('.list_paths'))
        else:
            messaging.flash(messaging.create_path_error)
    return render_template("paths/create.html", form=form, section='paths')


@blueprint.route('/<int:id>', methods=['GET', 'POST'])
def read_path(id):

    """ read a path and add page to path """

    record = tektonik.read_path(id)['result']

    return render_template(
        "paths/read.html",
        path=record,
        section='paths')


@blueprint.route('/<int:id>/pages', methods=['GET', 'POST'])
def page_schedule(id):

    """ view and add pages """

    record = tektonik.read_path(id)['result']
    data = {'path_id': id, 'page_id': 0}
    form = forms.PathPageForm(request.form, data=data)

    if request.method == 'POST':
        new_record = tektonik.create_path_page(request.form)
        is_valid = forms.is_valid(
            form,
            new_record,
            {'page_id': 'page_selector'}
        )
        if is_valid:
            messaging.flash(messaging.page_schedule_success)
            return redirect(url_for('.page_schedule', id=id))
        else:
            messaging.flash(messaging.page_schedule_error)

    return render_template(
        'paths/page_schedule.html',
        path=record,
        form=form,
        section='paths'
    )


@blueprint.route('/<int:id>/remove/<int:path_page_id>', methods=['GET'])
def remove_page(id, path_page_id):

    """ remove a page from a path """

    tektonik.delete_path_page(path_page_id)
    messaging.flash(messaging.remove_page_success)
    return redirect(url_for('.page_schedule', id=id))


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_path(id):

    """ edit a path """

    record = tektonik.read_path(id)['result']
    path_form = forms.path_form_factory(request, data=record)
    delete_form = forms.DeletePageForm(phrase=record['path'])

    if request.method == 'POST':
        form = forms.path_form_factory(request)
        update_record = tektonik.update_path(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_path_success)
            return redirect(url_for('.read_path', id=id))
        else:
            messaging.flash(messaging.update_path_error)

    template = "paths/update.html"
    return render_template(
        template,
        path_form=path_form,
        path=record,
        delete_form=delete_form,
        section='paths')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_path(id):

    """ delete a path """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_path_success,
            phrase=request.form['phrase'])
        tektonik.delete_path(id)
        return redirect(url_for('.list_paths'))
    else:
        messaging.flash(messaging.delete_path_error)
        return redirect(url_for('.read_path', id=id))

tekt/controllers/properties.py
"""
:synopsis: Properties controller
"""

from flask import Blueprint
from tekt.messaging import properties as messaging
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from tekt import forms
from tekt.tektonik import tektonik


blueprint = Blueprint('properties', __name__, template_folder='templates')


@blueprint.route('/')
def list_properties():

    """ get list of properties """
    properites = tektonik.list_properties()
    records = properites['result']
    metadata = properites['metadata']
    return render_template(
        "properties/list.html",
        properties=records,
        metadata=metadata,
        section='properties')


@blueprint.route('/create', methods=['GET', 'POST'])
def create_property():

    """ create a property """

    form = forms.PropertyForm(request.form)
    if request.method == 'POST':
        new_record = tektonik.create_property(request.form)
        is_valid = forms.is_valid(form, new_record)
        if is_valid:
            messaging.flash(messaging.create_property_success)
            return redirect(url_for('.list_properties'))
        else:
            messaging.flash(messaging.create_property_error)
    return render_template(
        "properties/create.html",
        form=form,
        section='properties')


@blueprint.route('/<int:id>')
def read_property(id):

    """ read a property """

    record = tektonik.read_property(id)['result']
    return render_template(
        "properties/read.html",
        property=record,
        section='properties')


@blueprint.route('/<int:id>/update', methods=['GET', 'POST'])
def update_property(id):

    """ edit a property """

    record = tektonik.read_property(id)['result']
    form = forms.PropertyForm(request.form, data=record)
    delete_form = forms.DeletePropertyForm(phrase=record['property'])

    if request.method == 'POST':
        form = forms.PropertyForm(request.form)
        update_record = tektonik.update_property(request.form, id)
        is_valid = forms.is_valid(form, update_record)
        if is_valid:
            messaging.flash(messaging.update_property_success)
            return redirect(url_for('.read_property', id=id))
        else:
            messaging.flash(messaging.update_property_error)

    template = "properties/update.html"
    return render_template(
        template,
        form=form,
        delete_form=delete_form,
        property=record,
        section='properties')


@blueprint.route('/<int:id>/delete', methods=['POST'])
def delete_property(id):

    """ delete a property """

    confirmed = request.form['phrase'] == request.form['confirm']

    if confirmed:
        messaging.flash(
            messaging.delete_property_success,
            phrase=request.form['phrase'])
        tektonik.delete_property(id)
        return redirect(url_for('.list_properties'))
    else:
        messaging.flash(messaging.delete_property_error)
        return redirect(url_for('.read_property', id=id))

tekt/templates/footer.html
<ul class="list utility">
    <li><a black href="">People</a></li>
    <li><a black href="">Perspectives</a></li>
    <li><a black href="">Plans</a></li>
    <li><a black href="">Primers</a></li>
</ul>

tekt/templates/home.html
{% from "macros/forms.html" import render_field %} 

<!DOCTYPE html>
<html> 
    <head>
        
        <title>{% block title %}TEKT{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/vendor.min.css') }}" />
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/styles.min.css') }}" />
        {% endblock %}

    </head>

    <body>
        
        <div id="splash" class="table" tekt-type="splash">
            <div class="tr">
                <div class="body td">
                    <a href="{{ url_for('main.dashboard') }}" id="logo" class="fa fa-play large animated fadeIn "></a>
                    <form id="sign-in-form" method="post" action="{{ url_for('main.home') }}">
                        <fieldset>
                            <ul>
                                <li>{{ form.username(placeholder='username') }}</li>
                                <li>{{ form.password(placeholder='password') }}</li>
                                <li>
                                    <input class="button" type="submit" value="sign in" />
                                </li>
                                <li><a>sign up</a>
                                </li>
                            </ul>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        </div>

        {% block scripts %}
            <script src="{{ url_for('static', filename='assets/vendor.min.js') }}"></script>
            <script src="{{ url_for('static', filename='assets/scripts.min.js') }}"></script>
            {% if config.DEBUG %}<script src="//localhost:35729/livereload.js"></script>{% endif %}
        {% endblock %}
        {% block page_scripts %}{% endblock %}

    </body>
</html>

tekt/templates/menu.html
{% from "macros/menus.html" import render_menu_link %} 
<div class="menu">
    <a href="{{ url_for('main.dashboard') }}" class="item logo animated fadeIn ">
        <span class="text"><span class="logo-font">ark</span></span>
        <span class="icon"><i class="logo-graphic fa fa-play"></i></span>
    </a>
    {{ render_menu_link(icon='fa ' + g.template['menu-toggle-button'], classes='toggle') }}
    {{ render_menu_link(text='Dashboard', link='main.dashboard', icon='fa fa-dashboard', section=(section == 'dashboard')) }}
    {{ render_menu_link(text='Properties', link='properties.list_properties', icon='fa fa-tree', section=(section == 'properties')) }}
    {{ render_menu_link(text='Paths', link='paths.list_paths', icon='fa fa-code-fork', section=(section == 'paths')) }}
    {{ render_menu_link(text='Pages', link='pages.list_pages', icon='fa fa-file-o', section=(section == 'pages')) }}
</div>

tekt/templates/menu_utility.html
<div id="menu_utility">
    <a href="">Perspectives</a>
    <a href="">Plans</a>
    <a href="">Primers</a>
</div>

tekt/templates/pages.html
{% extends "template.html" %}

{% block title %}
Pages
{% endblock %}

{% block body %}
<h1>Pages</h1>

<form method="POST" action="{{ url_for('.list_pages') }}">
    {{ form.csrf_token }}

    {% if form.page.errors %}
        <ul class="errors">{% for error in form.page.errors %}<li>{{ error }}</li>{% endfor %}</ul>
    {% endif %}
    {{ form.page.label }} {{ form.page(size=20, placeholder="aboutus") }}
    <input type="submit" value="Go">
</form>

<ul id="pages">

    {% for page in pages %}
    <li>
        <a href="{{ url_for('.read_page', id=page.id) }}">{{ page.page }}</a>
        <a href="{{ url_for('.delete_page', id=page.id) }}">Delete</a>
    </li>
    {% endfor %}

</ul>

{% endblock %}

tekt/templates/path.html
{% extends "template.html" %}

{% block title %}
Path
{% endblock %}

{% block body %}
<h1>Path</h1>

<ol>
<li><a href="{{ url_for('.read_update_property', id=path.property.id) }}">{{ path.property.property }}</a></li>
<li><a href="{{ url_for('.read_path', id=path.id) }}">{{ path.path }}</a></li>
</ol>

<h2>Pages</h2>

<form method="POST" action="{{ url_for('.read_path', id=path.id) }}">
    {{ form.csrf_token }}
    {{ form.path }}
    <ol>
        <li>
            {% if form.page.errors %}
            <ul class="errors">{% for error in form.page.errors %}
            <li>{{ error }}</li>{% endfor %}
            </ul>{% endif %} 
            {{ form.page.label }} {{ form.page }}
        </li>
    </ol>
    <input type="submit" value="Go">
</form>

<ul id="path_pages">

    {% for path_page in path_pages %}
    <li>
        {{ path_page.page.page }}
    </li>
    {% endfor %}

</ul>

{% endblock %}

tekt/templates/paths.html
{% extends "template.html" %} 
{% block title %} Paths {% endblock %} {% block body %}
<h1>Paths</h1>

{{ path_form(form) }}
{{ path_list(paths) }}

{% endblock %}

tekt/templates/primers.html
{% extends 'template.html' %}
{% block body %}
<h1>Primers</h1>
{% endblock %}

tekt/templates/properties-create.html
{% from "macros/forms.html" import render_field %} 
{% extends 'template.html' %} 

{% block body %}
<h1>Create Property</h1>
<form method="post" action="{{ url_for('.create_property') }}">
    <fieldset>
        <legend>Create Property</legend>
        <ul>
            {{ render_field(form.property, autofocus='autofocus') }}
        </ul>
    </fieldset>
    <fieldset>
        <input class="button" type="submit" value="save">
        <a class="button" href="{{ url_for('.properties') }}">cancel</a>
    </fieldset>
</form>
{% endblock %}

tekt/templates/properties-update.html
{% from "macros/forms.html" import render_field %} 
{% extends 'template.html' %} 

{% block body %}
<h1>Update Property</h1>
<form method="post" action="{{ url_for('.update_property', id=property.id) }}">
    {{ form.id }}
    <fieldset>
        <legend>Update Property</legend>
        <ul>
            {{ render_field(form.property, autofocus="autofocus") }}
        </ul>
    </fieldset>
    <fieldset>
        <input class="button" type="submit" value="save">
        <a class="button" href="{{ url_for('.properties') }}">cancel</a>
    </fieldset>
</form>
{% endblock %}

tekt/templates/properties.html
{% extends 'template.html' %}
{% block body %}
<div class="table">
    <div class="tr">
        <div class="td"><h1 class="td">Properties</h1></div>
        <div class="td"><a class="button" href="{{ url_for('.create_property') }}">create</a></div>
    </div>
</div>

<table>
    <tr>
        <th>Property</th>
        <th>Actions</th>
    </tr>
    {% for record in properties %}
    <tr>
        <td>
            <a href="{{ url_for('.read_property', id=record.id) }}">{{ record.property }}</a>
        </td>
        <td>
            <a class="button" href="{{ url_for('.update_property', id=record.id )}}">edit</a>
            <a class="button" href="{{ url_for('.delete_property', id=record.id )}}">delete</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tekt/templates/property.html
{% extends "template.html" %}

{% block title %}
Property
{% endblock %}

{% block body %}
<h1>Property</h1>

{{ property.property }}

<h2>Paths</h2>

{{ path_form(form, showProperty=False) }}
{{ path_list(property.paths, showProperty=False) }}

{% endblock %}

tekt/templates/template.focused.html
<!DOCTYPE html>
<html> 
    <head>
        
        <title>{% block title %}TEKT{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/vendor.min.css') }}" />
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/styles.min.css') }}" />
        {% endblock %}
        {% block page_styles %}{% endblock %}

    </head>

    <body>
        
        <div class="body">
            <div class="table">
                <div class="tr">
                    <div class="page td">
                        {% block body %}
                        {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% block scripts %}
            <script src="{{ url_for('static', filename='assets/vendor.min.js') }}"></script>
            <script src="{{ url_for('static', filename='assets/scripts.min.js') }}"></script>
            {% if config.DEBUG %}<script src="//localhost:35729/livereload.js"></script>{% endif %}
        {% endblock %}
        {% block page_scripts %}{% endblock %}

    </body>
</html>

tekt/templates/template.html
<!DOCTYPE html>
<html> 
    <head>
        
        <title>{% block title %}TEKT{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/vendor.min.css') }}" />
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/styles.min.css') }}" />
        {% endblock %}

    </head>

    <body>
        <div class="body">
            <a class="scroll-to-top" tekt-scroller="top=0" tekt-fixate>
                top <i class="fa fa-chevron-up"></i>
            </a>
            <div class="template" tekt-type="main">
                <div class="regions">
                    <div class="region left {{ g.template['menu-toggle'] }}">
                        {% include 'menu.html' %}
                    </div>
                    <div class="region right">
                        {% include 'messenger.html' %}
                        <div class="page">{% block body %}{% endblock %}</div>
                    </div>
                </div>
            </div>
        </div>

        {% block scripts %}
            <script src="{{ url_for('static', filename='assets/vendor.min.js') }}"></script>
            <script src="{{ url_for('static', filename='assets/scripts.min.js') }}"></script>
            {% if config.DEBUG %}<script src="//localhost:35729/livereload.js"></script>{% endif %}
        {% endblock %}
        {% block page_scripts %}{% endblock %}

    </body>
</html>